### ISSUE TITLE
can you supply the input file?

### ISSUE THREAD

**Issue by sunjunlishi** [robin1001/beamforming#1]
std::string input_file = po.GetArg(1),                 output_file = po.GetArg(2);
could you supply the input_file
我自己只能尝试生成双通道语音；距离啥的我也是尝试录制；
但最终没有看到效果；所以想用你的那个 输入语音文件 4ch.wav测试；
更好的理解你的代码

**Comment by robin1001** [comment]
sorry, i can't find that. 不好意思。

**Comment by sunjunlishi** [comment]
对了，我想增强某个方向的声音；我看了阵列书中延时求和的下一节是固定波束形成的设计加一个滤波器采用ls方法去求滤波器参数。你的代码能实现加强某个方向的声音的吗，你的那个延时加的代码，第一步求的是延时，是声源的延时吗？你下面的延时加求的是什么？

**Comment by sunjunlishi** [comment]
GSC 是不是 属于 固定 波束形成

**Comment by sunjunlishi** [comment]
声音我已经可以自己录制了，4个通道的。
你的mvdr也可以增强某个方向的声音吧

**Comment by sunjunlishi** [comment]
我已经测试，windows下 文件读取写入要加 "b"二进制形式，不然回失败。
gsc我尝试了，非常不错。
还有你的代码简单明了，清晰，非常 不错。还有 webrtc的 麦克风阵列算法也不错，就是损失精度有点大
特别是wav文件的读取写入。

**Comment by mjc14** [comment]
@sunjunlishi ，你的测试文件能发我一个调试一下吗？

**Comment by sunjunlishi** [comment]
已经不做那个，文件在公司机子上。
奥；你录双通道便可，如果两个文件波形不是一模一样的，说明是真的双通道；

**Comment by StuartIanNaylor** [comment]
4ch.wav

http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/Samples/SoundCardAttrition/4ch.wav
