### ISSUE TITLE
mvdr error ？

### ISSUE THREAD

**Issue by sunjunlishi** [robin1001/beamforming#2]
The code I ran MVDR seemed to have bug, crash

**Comment by sunjunlishi** [comment]
i have resolve it. 对了最终生成的语音文件，怎么是空白音呀。

**Comment by sunjunlishi** [comment]
空白音，已经解决 主要是 windows 下，文件读取写入还要加入 “b”二进制标志
崩溃暂时还没有解决

**Comment by xunwumizhi** [comment]
@sunjunlishi mvdr在VS下问题解决了吗

**Comment by xunwumizhi** [comment]
@sunjunlishi MVDR的bug怎么解决，能否指点指点，恳请解答 ^-^

**Comment by sunjunlishi** [comment]
上面写的崩溃暂时没解决，只是解决空白音。beamform 最好 用 webrtc的 beamform。

**Comment by xunwumizhi** [comment]
@sunjunlishi 我找到问题了，mvdr.h文件：

1.function DoBeamformimg形参int num_sample为帧长，与语音总长度num_sample混淆，应修改；
2. ComplexMatrix变量**alpha_tc**(1, num_channel_)，维度为（1，num_channel_），可是后面循环体内

>   for (int j = 0; j < num_channel_; j++) {
>                 //..............................................
>                 alpha_tc(0, j).real = cos(M_2PI * f * tdoa[j]);
>                 **alpha_tc(j, 0).img** = sin(M_2PI * f * tdoa[j]); //这一句维度有误
>             }

**Comment by sunjunlishi** [comment]
非常感谢，you are great.你可以加入此群，专门讨论麦克风阵列的383074754
